# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{deeply_valid}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Starr Horne"]
  s.date = %q{2010-06-07}
  s.description = %q{This gem lets you declaratively specify validations for complex data structures, like those returned from an api.}
  s.email = %q{starr@chromahq.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "deeply_valid.gemspec",
     "lib/deeply_valid.rb",
     "lib/deeply_valid/base.rb",
     "lib/deeply_valid/validation.rb",
     "lib/deeply_valid/validation_helpers.rb",
     "test/base_test.rb",
     "test/helper.rb",
     "test/system_test.rb",
     "test/validation_helpers_test.rb",
     "test/validation_test.rb"
  ]
  s.homepage = %q{http://github.com/starrhorne/deeply_valid}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Validation for complex data structures}
  s.test_files = [
    "test/base_test.rb",
     "test/helper.rb",
     "test/system_test.rb",
     "test/validation_helpers_test.rb",
     "test/validation_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

